numb1 = int(input("digite um numero"))
numb2 = int(input("digite mais um numero"))
numb3 = int(input("digite mais um numero"))
numb4 = int(input("digite mais um numero"))
numb5 = int(input("digite mais um numero"))
